name: Android Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew testDebugUnitTest

    - name: Generate code coverage report
      run: ./gradlew jacocoTestReport

    - name: Upload code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: app/build/reports/jacoco/jacocoTestReport.xml
